### ISSUE TITLE
TypeError: '>=' not supported between instances of 'NoneType' and 'int'

### ISSUE THREAD

**Issue by qycaitian** [NFJones/audio-to-midi#5]
Traceback (most recent call last):
  File "D:\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Programs\audio_to_midi\.venv\Scripts\audio-to-midi.exe\__main__.py", line 9, in <module>
  File "d:\programs\audio_to_midi\.venv\lib\site-packages\audio_to_midi\main.py", line 113, in main
    process.convert()
  File "d:\programs\audio_to_midi\.venv\lib\site-packages\audio_to_midi\converter.py", line 270, in convert
    writer.add_notes(midi_list)
  File "d:\programs\audio_to_midi\.venv\lib\site-packages\audio_to_midi\midi_writer.py", line 40, in add_notes
    if pitch >= 0:
TypeError: '>=' not supported between instances of 'NoneType' and 'int'

**Comment by qycaitian** [comment]
Seems the issue is fixed in your newest code. Would you please push the new version to pip?
